### ISSUE TITLE
Serve Static/Cached Response

### ISSUE THREAD

**Issue by ardatosun** [ardatosun/loadbalancer#14]
Implement functionality to serve static or pre-configured cached responses for specific URLs. This would enable the load balancer to respond directly with pre-configured content for certain endpoints without forwarding the request to the backend servers. This feature can improve performance and reduce load on backend services for certain types of requests.

#### Requirements:
- Allow specific URLs to be configured to return static/cached response
- Each response can be configured with a response body and status code (defaults to `empty response` and `HTTP 200 OK`)

#### Notes:
Caching part could have much more depth (e.g. different expiration policies, TTL) but it shouldn't be mandatory for first implementation

**Comment by ohyesgocool** [comment]
Hey , shall i pick this ? :)

**Comment by ardatosun** [comment]
hey @ohyesgocool , thanks, go ahead!
