### ISSUE TITLE
Status Page for backend monitoring

### ISSUE THREAD

**Issue by ardatosun** [ardatosun/loadbalancer#15]
This page will provide a high-level overview of the health and status of the backends managed by the load balancer. The goal is to get a basic frontend interface in place, which we can later expand.

#### Requirements:
1. Frontend UI:
    - A simple UI that displays the status of each backend.
    - React or Vue.js
2. Design:
    - List all backend
    - Basic health status indicator (e.g. green/red for health/unhealthy)
3. Backend data:
    - Use either mock data to begin with or build on top of the existing health checks

An example mock data could be like below for MVP:
```json
{
  "backends": [
    {
      "id": "server1",
      "ip_address": "192.168.1.101",
      "status": "healthy",
      "last_checked": "2024-10-20T18:00:00Z"
    },
    {
      "id": "server2",
      "ip_address": "192.168.1.102",
      "status": "unhealthy",
      "last_checked": "2024-10-20T18:00:00Z"
    },
    {
      "id": "server3",
      "ip_address": "192.168.1.103",
      "status": "healthy",
      "last_checked": "2024-10-20T18:00:00Z"
    }
  ]
}
```

**Comment by aetherfaye1009** [comment]
Hi hi, I would like to contribute on this issue, can you please assign this to me?
And also if I want to do it in `React`, do I just create a new folder called "frontend" inside the repo?

**Comment by ardatosun** [comment]
assigned @aetherfaye1009
