### ISSUE TITLE
Add Logging for Load Balancer Requests

### ISSUE THREAD

**Issue by ardatosun** [ardatosun/loadbalancer#3]
Implement logging for incoming requests and responses. This enhancement will help in monitoring and debugging.

- Add logging statements in the handleRequest function to log incoming requests (method, URL, and timestamp).
- Log the responses sent back to clients, including any errors that occur during request processing.
- Consider using a structured logging approach for easier analysis.

**Comment by ohyesgocool** [comment]
Hi , Can i Work on this ?

**Comment by ardatosun** [comment]
Hi, @ohyesgocool 
Assigned
