### ISSUE TITLE
Enhance Backend Health Check Mechanism

### ISSUE THREAD

**Issue by ardatosun** [ardatosun/loadbalancer#5]
The current health check implementation only pings the backends using TCP connections. To improve accuracy, we should enhance this mechanism to include HTTP status checks, allowing the load balancer to determine backend availability based on actual HTTP responses.

- Update the isBackendAlive function to send an HTTP GET request to each backend and check for a successful response (e.g., 200 OK).
- ~~Implement configurable health check endpoints for each backend. (e.g. /health)~~ Expose a single fixed path (e.g. /health) on backends that the load balancer should look for its health check

**Comment by ardatosun** [comment]
Thank you for your question @abuzaforfagun 

I see how my initial wording might have caused some confusion. To clarify: the load balancer should look for a single, fixed path (e.g., `/health`) on each backend for its health check. It would then be the responsibility of each backend to expose this specific endpoint for the load balancer to include them in the active backends pool.

So, while all backends would have to expose the same health check path (`/health`), they can each handle it internally as needed, but there wouldn’t be different health check URLs per backend (like `backend1/healthy`, `backend2/status`, etc.).

**Comment by abuzaforfagun** [comment]
That does make sense, I would like to work on this issue.

**Comment by ardatosun** [comment]
Assigned @abuzaforfagun
