### ISSUE TITLE
Implement Latency Measurement in Health Check Function

### ISSUE THREAD

**Issue by ohyesgocool** [ardatosun/loadbalancer#9]
Enhance our health check function to measure and track the latency of each server in our load balancer. 
This feature will provide valuable insights into server performance and also can be used to improve load balancing decisions.

**Server Object Update:** 

Modify the `Server` struct to include a field for storing latency information. This could be an average latency or a rolling window of recent measurements.

[reference](https://aws.amazon.com/blogs/aws/route-53-improvements-calculated-health-checks-and-latency-checks/)

**Comment by ohyesgocool** [comment]
If the enhancement sounds okay , you can assign it to me. 
Thanks ! @ardatosun

**Comment by ardatosun** [comment]
Sounds good! I was thinking of extending the load balancing strategies and this enhancement would be useful when doing that (e.g. least latency instead of just round-robin)

assigned now @ohyesgocool
